# -*- coding: utf-8 -*-
"""Copy of Apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktnwJXRSXY8ENoEKc4lV1_MctVuN2QTV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("BigBasket.csv")
trans= []
for i in range(0,7218):
    trans.append([str(df.values[i,j]) for j in range(0,20)])

from apyori import apriori
basket = apriori(transactions = trans, min_support = 0.002, min_confidence = 0.2, min_lift = 3, min_length = 2, max_lenght = 2)

results = list(basket)
results

def inspect(results):
    product1         = [tuple(result[2][0][0])[0] for result in results]
    product2         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(product1, product2, supports, confidences, lifts))
DataFrame_intelligence = pd.DataFrame(inspect(results), columns = ['product1', 'product2', 'Support', 'Confidence', 'Lift'])

DataFrame_intelligence

similar_df = DataFrame_intelligence[DataFrame_intelligence['product1'] == 'chicken']
products = similar_df.nlargest(5, 'Confidence')
print(products)